apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference base resources
resources:
- ../../base/namespace.yaml
- ../../base/api-deployment.yaml
- ../../base/api-service.yaml
- ../../base/web-deployment.yaml
- ../../base/web-service.yaml
- ../../base/worker-deployment.yaml

# Development namespace
namespace: revenue-platform-dev

# Common labels for all resources
commonLabels:
  environment: development
  managed-by: kustomize
  debug-enabled: "true"

# Development-specific patches
patches:
# API Deployment patches
- target:
    kind: Deployment
    name: api-deployment
  patch:
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: api
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "1"
                memory: "2Gi"
            env:
            - name: NODE_ENV
              value: "development"
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: ENABLE_SWAGGER
              value: "true"
            livenessProbe:
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              initialDelaySeconds: 20
              periodSeconds: 5

# Web Deployment patches
- target:
    kind: Deployment
    name: web-deployment
  patch:
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: web
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "200m"
                memory: "512Mi"
            env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_API_URL
              value: "http://api-service:3000"
            - name: ENABLE_DEBUG_TOOLS
              value: "true"
            - name: REACT_DEVTOOLS
              value: "true"

# Worker Deployment patches
- target:
    kind: Deployment
    name: worker-deployment
  patch:
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: worker
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "1"
                memory: "2Gi"
            env:
            - name: NODE_ENV
              value: "development"
            - name: DEBUG
              value: "true"
            - name: ENABLE_PROFILING
              value: "true"
            - name: MOCK_EXTERNAL_SERVICES
              value: "true"