openapi: 3.0.3
info:
  title: Campaign Management API Schema
  version: 1.0.0
  description: OpenAPI schema definitions for campaign management in the autonomous revenue generation platform

components:
  schemas:
    Campaign:
      type: object
      required:
        - id
        - organizationId
        - name
        - status
        - type
        - configuration
        - startDate
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the campaign
          example: "123e4567-e89b-12d3-a456-426614174000"
        organizationId:
          type: string
          format: uuid
          description: Organization that owns the campaign
          example: "123e4567-e89b-12d3-a456-426614174001"
        name:
          type: string
          minLength: 3
          maxLength: 100
          description: Name of the campaign
          example: "Q4 2023 Enterprise Outreach"
        description:
          type: string
          maxLength: 500
          description: Detailed description of the campaign
          example: "Automated outreach campaign targeting enterprise tech companies"
        status:
          type: string
          enum: [DRAFT, SCHEDULED, ACTIVE, PAUSED, COMPLETED, ARCHIVED]
          description: Current status of the campaign
          example: "ACTIVE"
        type:
          type: string
          enum: [OUTBOUND_CALL, SOCIAL_MEDIA, EMAIL_SEQUENCE, MULTI_CHANNEL]
          description: Type of campaign
          example: "OUTBOUND_CALL"
        configuration:
          type: object
          required:
            - channels
            - content
            - schedule
          properties:
            channels:
              type: array
              items:
                type: string
                enum: [LINKEDIN, TWITTER, TIKTOK, EMAIL, VOICE]
              description: Distribution channels for the campaign
            content:
              type: array
              items:
                $ref: '#/components/schemas/CampaignContent'
            schedule:
              type: object
              properties:
                timezone:
                  type: string
                  description: Campaign timezone
                  example: "America/Los_Angeles"
                activeHours:
                  type: object
                  properties:
                    start:
                      type: string
                      pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
                      example: "09:00"
                    end:
                      type: string
                      pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
                      example: "17:00"
                    days:
                      type: array
                      items:
                        type: integer
                        minimum: 0
                        maximum: 6
                throttling:
                  type: object
                  properties:
                    maxPerHour:
                      type: integer
                      minimum: 1
                      example: 100
                    maxPerDay:
                      type: integer
                      minimum: 1
                      example: 1000
        metrics:
          $ref: '#/components/schemas/CampaignMetrics'
        budget:
          $ref: '#/components/schemas/CampaignBudget'
        targeting:
          $ref: '#/components/schemas/CampaignTargeting'
        aiConfig:
          $ref: '#/components/schemas/CampaignAIConfig'
        startDate:
          type: string
          format: date-time
          description: Campaign start date
        endDate:
          type: string
          format: date-time
          nullable: true
          description: Campaign end date
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    CampaignContent:
      type: object
      required:
        - type
        - platform
        - content
        - schedule
      properties:
        type:
          type: string
          enum: [TEXT, IMAGE, AUDIO, DOCUMENT, VIDEO]
        platform:
          type: string
          enum: [LINKEDIN, TWITTER, TIKTOK, EMAIL, VOICE]
        content:
          oneOf:
            - type: string
            - type: object
        schedule:
          type: object
          properties:
            startTime:
              type: string
              format: date-time
            frequency:
              type: string
            timezone:
              type: string
        variations:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              content:
                oneOf:
                  - type: string
                  - type: object
              performance:
                $ref: '#/components/schemas/CampaignMetrics'

    CampaignMetrics:
      type: object
      properties:
        performance:
          type: array
          items:
            $ref: '#/components/schemas/Metric'
        engagement:
          type: object
          properties:
            impressions:
              type: integer
              minimum: 0
            interactions:
              type: integer
              minimum: 0
            conversions:
              type: integer
              minimum: 0
            conversionRate:
              type: number
              minimum: 0
              maximum: 100
        revenue:
          type: object
          properties:
            generated:
              type: number
              minimum: 0
            projected:
              type: number
              minimum: 0
            roi:
              type: number
        quality:
          type: object
          properties:
            leadScore:
              type: number
              minimum: 0
              maximum: 100
            responseRate:
              type: number
              minimum: 0
              maximum: 100
            satisfactionScore:
              type: number
              minimum: 0
              maximum: 100

    CampaignBudget:
      type: object
      required:
        - totalBudget
        - dailyLimit
        - currency
      properties:
        totalBudget:
          type: number
          minimum: 0
        dailyLimit:
          type: number
          minimum: 0
        currency:
          type: string
          example: "USD"
        costPerAction:
          type: object
          additionalProperties:
            type: number
        alerts:
          type: object
          properties:
            thresholds:
              type: array
              items:
                type: number
            notifications:
              type: array
              items:
                type: string

    CampaignTargeting:
      type: object
      required:
        - audience
      properties:
        audience:
          type: object
          properties:
            industries:
              type: array
              items:
                type: string
            companySize:
              type: array
              items:
                type: string
            roles:
              type: array
              items:
                type: string
            geography:
              type: array
              items:
                type: string
        exclusions:
          type: object
          properties:
            industries:
              type: array
              items:
                type: string
            companies:
              type: array
              items:
                type: string
            domains:
              type: array
              items:
                type: string

    CampaignAIConfig:
      type: object
      required:
        - modelType
        - temperature
        - maxTokens
        - customPrompts
      properties:
        modelType:
          type: string
        temperature:
          type: number
          minimum: 0
          maximum: 1
        maxTokens:
          type: integer
          minimum: 1
        voiceId:
          type: string
        customPrompts:
          type: object
          additionalProperties:
            type: string
        contextWindow:
          type: integer
          minimum: 1
        optimizationGoals:
          type: array
          items:
            type: string
        learningRate:
          type: number
          minimum: 0
          maximum: 1
        retrainingInterval:
          type: integer
          minimum: 1

    Metric:
      type: object
      required:
        - type
        - value
        - unit
        - timestamp
      properties:
        type:
          type: string
          enum: [LATENCY, THROUGHPUT, ERROR_RATE, CONCURRENT_USERS, UPTIME, QUERY_TIME, VOICE_LATENCY, CONTENT_GENERATION_TIME, REVENUE, CONVERSION_RATE]
        value:
          type: number
        unit:
          type: string
          enum: [ms, req/s, q/s, %, uptime_%, count, USD, w/m]
        timestamp:
          type: string
          format: date-time