openapi: 3.0.0
components:
  schemas:
    Lead:
      type: object
      description: Enhanced lead schema with comprehensive validation and security features
      required:
        - id
        - campaignId
        - email
        - status
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the lead
          readOnly: true
        campaignId:
          type: string
          format: uuid
          description: Associated campaign identifier
        email:
          type: string
          format: email
          description: Lead's email address
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          maxLength: 255
        firstName:
          type: string
          description: Lead's first name
          maxLength: 100
          pattern: "^[\\p{L}\\s'-]+$"
        lastName:
          type: string
          description: Lead's last name
          maxLength: 100
          pattern: "^[\\p{L}\\s'-]+$"
        company:
          type: string
          description: Lead's company name
          maxLength: 200
        title:
          type: string
          description: Lead's job title
          maxLength: 150
        phone:
          type: string
          description: Lead's phone number
          pattern: '^\+?[1-9]\d{1,14}$'
          maxLength: 20
        score:
          type: integer
          minimum: 0
          maximum: 100
          default: 0
          description: Lead qualification score based on AI analysis
        status:
          type: string
          enum:
            - NEW
            - QUALIFYING
            - QUALIFIED
            - NURTURING
            - CONVERTED
            - DISQUALIFIED
          default: NEW
          description: Current status of the lead in the pipeline
        source:
          type: string
          enum:
            - OUTBOUND_CALL
            - LINKEDIN
            - TWITTER
            - TIKTOK
            - EMAIL
            - WEBSITE
            - FORM
          description: Source channel of lead acquisition
        metadata:
          type: object
          properties:
            industry:
              type: string
              maxLength: 100
            companySize:
              type: string
              enum:
                - 1-10
                - 11-50
                - 51-200
                - 201-1000
                - 1001+
            location:
              type: object
              properties:
                country:
                  type: string
                  maxLength: 100
                state:
                  type: string
                  maxLength: 100
                city:
                  type: string
                  maxLength: 100
            budget:
              type: object
              properties:
                range:
                  type: string
                  enum:
                    - 0-10K
                    - 10K-50K
                    - 50K-200K
                    - 200K+
                currency:
                  type: string
                  default: USD
            interests:
              type: array
              items:
                type: string
              maxItems: 20
            tags:
              type: array
              items:
                type: string
              maxItems: 50
          description: Enhanced metadata about the lead
        interactions:
          type: array
          items:
            $ref: '#/components/schemas/LeadInteraction'
          description: History of lead interactions
          maxItems: 1000
        complianceInfo:
          type: object
          properties:
            gdprConsent:
              type: boolean
              description: GDPR consent status
            ccpaOptOut:
              type: boolean
              description: CCPA opt-out status
            dataRetention:
              type: string
              format: date-time
              description: Data retention expiry date
          description: Compliance and data protection information
        createdAt:
          type: string
          format: date-time
          description: Timestamp of lead creation
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Timestamp of last update
          readOnly: true

    LeadInteraction:
      description: Enhanced schema for tracking lead interactions with detailed metadata
      type: object
      required:
        - id
        - type
        - timestamp
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the interaction
          readOnly: true
        type:
          type: string
          enum:
            - CALL
            - EMAIL
            - SOCIAL
            - WEBSITE
            - FORM
            - CHAT
          description: Type of interaction
        channel:
          type: string
          description: Specific channel of interaction
          maxLength: 100
        content:
          type: string
          description: Content or summary of interaction
          maxLength: 5000
        sentiment:
          type: string
          enum:
            - POSITIVE
            - NEUTRAL
            - NEGATIVE
          description: AI-analyzed sentiment of interaction
        metadata:
          type: object
          properties:
            duration:
              type: integer
              description: Duration in seconds for calls
            url:
              type: string
              format: uri
              description: Related URL if applicable
            location:
              type: string
              description: Geographic location of interaction
          description: Additional interaction metadata
        timestamp:
          type: string
          format: date-time
          description: Timestamp of interaction
          readOnly: true