apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revenue-platform

resources:
  - ../../base/namespace.yaml
  - ../../base/api-deployment.yaml
  - ../../base/api-service.yaml
  - ../../base/web-deployment.yaml
  - ../../base/web-service.yaml
  - ../../base/worker-deployment.yaml

patches:
  # API Deployment production patches
  - target:
      kind: Deployment
      name: api-deployment
    patch:
      spec:
        replicas: 4
        template:
          spec:
            containers:
              - name: api
                resources:
                  requests:
                    cpu: "2"
                    memory: "4Gi"
                  limits:
                    cpu: "4"
                    memory: "8Gi"
                livenessProbe:
                  httpGet:
                    path: /health
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 10
                readinessProbe:
                  httpGet:
                    path: /ready
                    port: 8080
                  initialDelaySeconds: 15
                  periodSeconds: 5
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    app: api

  # Web Deployment production patches
  - target:
      kind: Deployment
      name: web-deployment
    patch:
      spec:
        replicas: 4
        template:
          spec:
            containers:
              - name: web
                resources:
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
                  limits:
                    cpu: "1"
                    memory: "2Gi"
                livenessProbe:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 20
                  periodSeconds: 10

  # Worker Deployment production patches
  - target:
      kind: Deployment
      name: worker-deployment
    patch:
      spec:
        replicas: 4
        template:
          spec:
            containers:
              - name: worker
                resources:
                  requests:
                    cpu: "2"
                    memory: "4Gi"
                  limits:
                    cpu: "4"
                    memory: "8Gi"
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      topologyKey: kubernetes.io/hostname

configMapGenerator:
  - name: revenue-platform-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - MONITORING_ENABLED=true
      - TRACING_ENABLED=true
      - METRICS_INTERVAL=30
      - MAX_CONCURRENT_REQUESTS=10000
      - CACHE_TTL=3600
      - RATE_LIMIT_ENABLED=true

images:
  - name: api
    newName: ${ECR_REGISTRY}/revenue-platform-api
    newTag: ${IMAGE_TAG}
  - name: web
    newName: ${ECR_REGISTRY}/revenue-platform-web
    newTag: ${IMAGE_TAG}
  - name: worker
    newName: ${ECR_REGISTRY}/revenue-platform-worker
    newTag: ${IMAGE_TAG}